name: kstream
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^5.0.1
  flutter:
    sdk: flutter
  get: 4.6.5
  google_fonts: ^4.0.3
  logger: ^1.2.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/dummy/
