name: kstream
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  chewie: ^1.4.0
  cupertino_icons: ^1.0.2
  dio: ^5.0.1
  flutter:
    sdk: flutter
  flutter_inappwebview: ^5.7.2+3
  get: 4.6.5
  google_fonts: ^4.0.3
  logger: ^1.2.2
  startapp_sdk: ^0.4.1
  video_player: ^2.5.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/dummy/
